spring:
  application:
         name: uni-cms

  flyway:
    enabled: true
    locations: classpath:/db/migration
    target: latest
    baseline-version: 1
    baseline-on-migrate: true
    clean-disabled: true
    

  datasource:
    url: jdbc:postgresql://localhost:5436/uni-cms?stringtype=unspecified
    username: postgres
    password: 22305

    hibernate:
      ddl-auto: none

logging:
  level:
    org.flywaydb: DEBUG

subject:
  generator:
    min-per-lecturer: 1
    max-per-lecturer: 3

