spring:
  application:
         name: uni-cms
  messages:
    basename: lang/messages
    encoding: UTF-8

  flyway:
    enabled: true
    locations: classpath:/db/migration
    target: latest
    baseline-version: 1
    baseline-on-migrate: true
    clean-disabled: true

  datasource:
    url: jdbc:postgresql://localhost:5436/uni-cms?stringtype=unspecified
    username: postgres
    password: 22305

    hibernate:
      ddl-auto: none

logging:
  level:
    org.flywaydb: DEBUG

subject:
  generator:
    min_per_lecturer: 1
    max_per_lecturer: 3

lesson:
  validation:
    min_duration_minutes: 45
    max_duration_minutes: 90

